/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpsIndexRouteImport } from './routes/ops.index'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as OpsInsightsRouteImport } from './routes/ops.insights'
import { Route as OpsComplaintsRouteImport } from './routes/ops.complaints'
import { Route as OpsAnalyticsRouteImport } from './routes/ops.analytics'
import { Route as CustomerTrackRouteImport } from './routes/customer.track'
import { Route as CustomerRaiseRouteImport } from './routes/customer.raise'
import { Route as CustomerInsightsRouteImport } from './routes/customer.insights'
import { Route as CustomerComplaintsRouteImport } from './routes/customer.complaints'

const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const OpsInsightsRoute = OpsInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => OpsRoute,
} as any)
const OpsComplaintsRoute = OpsComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => OpsRoute,
} as any)
const OpsAnalyticsRoute = OpsAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => OpsRoute,
} as any)
const CustomerTrackRoute = CustomerTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerRaiseRoute = CustomerRaiseRouteImport.update({
  id: '/raise',
  path: '/raise',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerInsightsRoute = CustomerInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerComplaintsRoute = CustomerComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => CustomerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/customer/complaints': typeof CustomerComplaintsRoute
  '/customer/insights': typeof CustomerInsightsRoute
  '/customer/raise': typeof CustomerRaiseRoute
  '/customer/track': typeof CustomerTrackRoute
  '/ops/analytics': typeof OpsAnalyticsRoute
  '/ops/complaints': typeof OpsComplaintsRoute
  '/ops/insights': typeof OpsInsightsRoute
  '/customer/': typeof CustomerIndexRoute
  '/ops/': typeof OpsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/customer/complaints': typeof CustomerComplaintsRoute
  '/customer/insights': typeof CustomerInsightsRoute
  '/customer/raise': typeof CustomerRaiseRoute
  '/customer/track': typeof CustomerTrackRoute
  '/ops/analytics': typeof OpsAnalyticsRoute
  '/ops/complaints': typeof OpsComplaintsRoute
  '/ops/insights': typeof OpsInsightsRoute
  '/customer': typeof CustomerIndexRoute
  '/ops': typeof OpsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/customer/complaints': typeof CustomerComplaintsRoute
  '/customer/insights': typeof CustomerInsightsRoute
  '/customer/raise': typeof CustomerRaiseRoute
  '/customer/track': typeof CustomerTrackRoute
  '/ops/analytics': typeof OpsAnalyticsRoute
  '/ops/complaints': typeof OpsComplaintsRoute
  '/ops/insights': typeof OpsInsightsRoute
  '/customer/': typeof CustomerIndexRoute
  '/ops/': typeof OpsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customer'
    | '/login'
    | '/ops'
    | '/customer/complaints'
    | '/customer/insights'
    | '/customer/raise'
    | '/customer/track'
    | '/ops/analytics'
    | '/ops/complaints'
    | '/ops/insights'
    | '/customer/'
    | '/ops/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/customer/complaints'
    | '/customer/insights'
    | '/customer/raise'
    | '/customer/track'
    | '/ops/analytics'
    | '/ops/complaints'
    | '/ops/insights'
    | '/customer'
    | '/ops'
  id:
    | '__root__'
    | '/'
    | '/customer'
    | '/login'
    | '/ops'
    | '/customer/complaints'
    | '/customer/insights'
    | '/customer/raise'
    | '/customer/track'
    | '/ops/analytics'
    | '/ops/complaints'
    | '/ops/insights'
    | '/customer/'
    | '/ops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerRoute: typeof CustomerRouteWithChildren
  LoginRoute: typeof LoginRoute
  OpsRoute: typeof OpsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/ops/insights': {
      id: '/ops/insights'
      path: '/insights'
      fullPath: '/ops/insights'
      preLoaderRoute: typeof OpsInsightsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/complaints': {
      id: '/ops/complaints'
      path: '/complaints'
      fullPath: '/ops/complaints'
      preLoaderRoute: typeof OpsComplaintsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/analytics': {
      id: '/ops/analytics'
      path: '/analytics'
      fullPath: '/ops/analytics'
      preLoaderRoute: typeof OpsAnalyticsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/customer/track': {
      id: '/customer/track'
      path: '/track'
      fullPath: '/customer/track'
      preLoaderRoute: typeof CustomerTrackRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/raise': {
      id: '/customer/raise'
      path: '/raise'
      fullPath: '/customer/raise'
      preLoaderRoute: typeof CustomerRaiseRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/insights': {
      id: '/customer/insights'
      path: '/insights'
      fullPath: '/customer/insights'
      preLoaderRoute: typeof CustomerInsightsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/complaints': {
      id: '/customer/complaints'
      path: '/complaints'
      fullPath: '/customer/complaints'
      preLoaderRoute: typeof CustomerComplaintsRouteImport
      parentRoute: typeof CustomerRoute
    }
  }
}

interface CustomerRouteChildren {
  CustomerComplaintsRoute: typeof CustomerComplaintsRoute
  CustomerInsightsRoute: typeof CustomerInsightsRoute
  CustomerRaiseRoute: typeof CustomerRaiseRoute
  CustomerTrackRoute: typeof CustomerTrackRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerComplaintsRoute: CustomerComplaintsRoute,
  CustomerInsightsRoute: CustomerInsightsRoute,
  CustomerRaiseRoute: CustomerRaiseRoute,
  CustomerTrackRoute: CustomerTrackRoute,
  CustomerIndexRoute: CustomerIndexRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface OpsRouteChildren {
  OpsAnalyticsRoute: typeof OpsAnalyticsRoute
  OpsComplaintsRoute: typeof OpsComplaintsRoute
  OpsInsightsRoute: typeof OpsInsightsRoute
  OpsIndexRoute: typeof OpsIndexRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsAnalyticsRoute: OpsAnalyticsRoute,
  OpsComplaintsRoute: OpsComplaintsRoute,
  OpsInsightsRoute: OpsInsightsRoute,
  OpsIndexRoute: OpsIndexRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerRoute: CustomerRouteWithChildren,
  LoginRoute: LoginRoute,
  OpsRoute: OpsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
